services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    depends_on:
      - db
    volumes:
      - ./backend:/app/backend
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - PORT=18000
    ports:
      - "18000:18000"
    command: uvicorn app:app --host 0.0.0.0 --port ${PORT} --reload

  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "18080:80"
    depends_on:
      - backend

volumes:
  pgdata: