# .github/workflows/deploy-to-hf.yml

name: Deploy to Hugging Face Spaces

on:
  # 当推送到 main 分支时触发
  push:
    branches:
      - main
  # 允许手动触发
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 运行环境

    steps:
      # 第一步：检出你的代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取所有历史记录，以便 lfs 工作

      # 可选步骤：设置 Python 环境并安装依赖
      # 如果你的 Space 需要特定版本的 Python 或有依赖项，这一步很有用
      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10' # 根据你的需要修改版本
      # - name: Install dependencies
      #   run: pip install -r requirements.txt

      # 可选步骤：运行测试
      # 在部署前确保代码质量
      # - name: Run tests
      #   run: pytest

      # 核心步骤：将代码推送到 Hugging Face Space
      - name: Push to Hugging Face Hub
        uses: huggingface/hub-action@v1 # 使用官方的 action
        with:
          # 你的 Hugging Face 用户名/组织名
          repo_owner: enty411
          # 你的 Hugging Face Space 仓库名
          repo_name: nikke-union-management
          # 目标仓库类型，对于 Space 来说是 "space"
          repo_type: space
          # 使用我们之前设置的 secret
          hf_token: ${{ secrets.HF_TOKEN }}
          # 设定 Space 的 SDK (e.g., streamlit, gradio, docker)
          # 如果你的 Space 是 Docker 类型的，就不需要这个
          # space_sdk: streamlit # 或者 gradio