# 这个工作流的名称，会显示在 GitHub 的 Actions 标签页中
name: Sync to Hugging Face Spaces

# --- 触发条件 ---
# 1. 当有代码被推送到 main 分支时
# 2. 允许你在 Actions 页面手动点击运行
on:
  push:
    branches:
      - main
  workflow_dispatch:

# --- 工作任务 ---
jobs:
  # 定义一个名为 'sync-to-hub' 的任务
  sync-to-hub:
    # 在最新的 Ubuntu 虚拟环境中运行
    runs-on: ubuntu-latest
    
    # 任务步骤
    steps:
      # 第一步：检出（下载）你的代码到虚拟环境中
      # 使用 actions/checkout@v4 是目前的最新稳定版
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # fetch-depth: 0 拉取所有 git 历史，对于 LFS 是必需的
          fetch-depth: 0
          # lfs: true 明确告诉 action 要处理 Git LFS 文件
          lfs: true

      # 第二步：使用 Git Push 命令将代码推送到 Hugging Face Hub
      - name: Push to Hugging Face Hub
        # 设置环境变量，将 GitHub Secret 安全地注入
        env:
          # HF_TOKEN 这个名字可以任意取，但要与下面的 $HF_TOKEN 对应
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        # 运行的核心命令
        # 我们在这里构建了一个包含认证信息的 git URL
        # 格式: https://<你的用户名>:<你的Token>@huggingface.co/spaces/<你的用户名>/<你的空间名>
        run: git push --force https://enty411:$HF_TOKEN@huggingface.co/spaces/enty411/nikke-union-management main